"""time start, end datetime type

Revision ID: 878b9c30c8e6
Revises: 978867cffd94
Create Date: 2025-03-19 20:51:01.071427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878b9c30c8e6'
down_revision: Union[str, None] = '978867cffd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentations', 'time_start',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False,
                postgresql_using="time_start::TEXT::TIMESTAMP")
    op.alter_column('presentations', 'time_end',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False,
                postgresql_using="time_start::TEXT::TIMESTAMP")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentations', 'time_end',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('presentations', 'time_start',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
